apiVersion: v1
items:
- apiVersion: keda.sh/v1alpha1
  kind: ScaledObject
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"keda.sh/v1alpha1","kind":"ScaledObject","metadata":{"annotations":{},"name":"vllm-autoscaler","namespace":"llm-gateway"},"spec":{"maxReplicaCount":1,"minReplicaCount":0,"scaleTargetRef":{"name":"vllm"},"triggers":[{"metadata":{"address":"redis.llm-gateway.svc.cluster.local:6379","listLength":"5","listName":"inference_queue"},"type":"redis"}]}}
    creationTimestamp: "2026-09-25T11:21:18Z"
    finalizers:
    - finalizer.keda.sh
    generation: 1
    labels:
      scaledobject.keda.sh/name: vllm-autoscaler
    name: vllm-autoscaler
    namespace: llm-gateway
    resourceVersion: "1790340168859055005"
    uid: 9d5f733d-78ab-4e89-8fc0-a904d4ff3f63
  spec:
    maxReplicaCount: 1
    minReplicaCount: 0
    scaleTargetRef:
      name: vllm
    triggers:
    - metadata:
        address: redis.llm-gateway.svc.cluster.local:6379
        listLength: "5"
        listName: inference_queue
      type: redis
  status:
    authenticationsTypes: ""
    conditions:
    - message: ScaledObject is defined correctly and is ready for scaling
      reason: ScaledObjectReady
      status: "True"
      type: Ready
    - message: Scaling is not performed because triggers are not active
      reason: ScalerNotActive
      status: "False"
      type: Active
    - message: No fallbacks are active on this scaled object
      reason: NoFallbackFound
      status: "False"
      type: Fallback
    - status: "False"
      type: Paused
    - message: scaling is disabled since the replica count of the target is zero
      reason: ScalingDisabled
      status: "True"
      type: HPAActive
    externalMetricNames:
    - s0-redis-inference_queue
    hpaName: keda-hpa-vllm-autoscaler
    lastActiveTime: "2026-09-25T12:34:18Z"
    originalReplicaCount: 0
    scaleTargetGVKR:
      group: apps
      kind: Deployment
      resource: deployments
      version: v1
    scaleTargetKind: apps/v1.Deployment
    triggersActivity:
      s0-redis-inference_queue:
        isActive: false
    triggersTypes: redis
- apiVersion: keda.sh/v1alpha1
  kind: ScaledObject
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"keda.sh/v1alpha1","kind":"ScaledObject","metadata":{"annotations":{},"name":"worker-autoscaler","namespace":"llm-gateway"},"spec":{"maxReplicaCount":2,"minReplicaCount":0,"scaleTargetRef":{"name":"worker"},"triggers":[{"metadata":{"address":"redis.llm-gateway.svc.cluster.local:6379","listLength":"5","listName":"inference_queue"},"type":"redis"}]}}
    creationTimestamp: "2026-09-25T11:21:16Z"
    finalizers:
    - finalizer.keda.sh
    generation: 1
    labels:
      scaledobject.keda.sh/name: worker-autoscaler
    name: worker-autoscaler
    namespace: llm-gateway
    resourceVersion: "1790340166985871019"
    uid: 21601533-891a-4656-a046-34cd57fc36fc
  spec:
    maxReplicaCount: 2
    minReplicaCount: 0
    scaleTargetRef:
      name: worker
    triggers:
    - metadata:
        address: redis.llm-gateway.svc.cluster.local:6379
        listLength: "5"
        listName: inference_queue
      type: redis
  status:
    authenticationsTypes: ""
    conditions:
    - message: ScaledObject is defined correctly and is ready for scaling
      reason: ScaledObjectReady
      status: "True"
      type: Ready
    - message: Scaling is not performed because triggers are not active
      reason: ScalerNotActive
      status: "False"
      type: Active
    - message: No fallbacks are active on this scaled object
      reason: NoFallbackFound
      status: "False"
      type: Fallback
    - status: "False"
      type: Paused
    - message: scaling is disabled since the replica count of the target is zero
      reason: ScalingDisabled
      status: "True"
      type: HPAActive
    externalMetricNames:
    - s0-redis-inference_queue
    hpaName: keda-hpa-worker-autoscaler
    lastActiveTime: "2026-09-25T12:34:16Z"
    originalReplicaCount: 0
    scaleTargetGVKR:
      group: apps
      kind: Deployment
      resource: deployments
      version: v1
    scaleTargetKind: apps/v1.Deployment
    triggersActivity:
      s0-redis-inference_queue:
        isActive: false
    triggersTypes: redis
- apiVersion: autoscaling/v2
  kind: HorizontalPodAutoscaler
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"keda.sh/v1alpha1","kind":"ScaledObject","metadata":{"annotations":{},"name":"vllm-autoscaler","namespace":"llm-gateway"},"spec":{"maxReplicaCount":1,"minReplicaCount":0,"scaleTargetRef":{"name":"vllm"},"triggers":[{"metadata":{"address":"redis.llm-gateway.svc.cluster.local:6379","listLength":"5","listName":"inference_queue"},"type":"redis"}]}}
    creationTimestamp: "2026-09-25T11:21:18Z"
    labels:
      app.kubernetes.io/managed-by: keda-operator
      app.kubernetes.io/name: keda-hpa-vllm-autoscaler
      app.kubernetes.io/part-of: vllm-autoscaler
      app.kubernetes.io/version: 2.21.0
      scaledobject.keda.sh/name: vllm-autoscaler
    name: keda-hpa-vllm-autoscaler
    namespace: llm-gateway
    ownerReferences:
    - apiVersion: keda.sh/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: ScaledObject
      name: vllm-autoscaler
      uid: 9d5f733d-78ab-4e89-8fc0-a904d4ff3f63
    resourceVersion: "1790340155991183014"
    uid: be1e0db8-1963-4135-a570-233bfbebbf34
  spec:
    maxReplicas: 1
    metrics:
    - external:
        metric:
          name: s0-redis-inference_queue
          selector:
            matchLabels:
              scaledobject.keda.sh/name: vllm-autoscaler
        target:
          averageValue: "5"
          type: AverageValue
      type: External
    minReplicas: 1
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: vllm
  status:
    conditions:
    - lastTransitionTime: "2026-09-25T12:31:05Z"
      message: recommended size matches current size
      reason: ReadyForNewScale
      status: "True"
      type: AbleToScale
    - lastTransitionTime: "2026-09-25T12:42:35Z"
      message: scaling is disabled since the replica count of the target is zero
      reason: ScalingDisabled
      status: "False"
      type: ScalingActive
    - lastTransitionTime: "2026-09-25T12:31:05Z"
      message: the desired replica count is less than the minimum replica count
      reason: TooFewReplicas
      status: "True"
      type: ScalingLimited
    currentMetrics:
    - external:
        current:
          averageValue: "0"
        metric:
          name: s0-redis-inference_queue
          selector:
            matchLabels:
              scaledobject.keda.sh/name: vllm-autoscaler
      type: External
    desiredReplicas: 0
- apiVersion: autoscaling/v2
  kind: HorizontalPodAutoscaler
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"keda.sh/v1alpha1","kind":"ScaledObject","metadata":{"annotations":{},"name":"worker-autoscaler","namespace":"llm-gateway"},"spec":{"maxReplicaCount":2,"minReplicaCount":0,"scaleTargetRef":{"name":"worker"},"triggers":[{"metadata":{"address":"redis.llm-gateway.svc.cluster.local:6379","listLength":"5","listName":"inference_queue"},"type":"redis"}]}}
    creationTimestamp: "2026-09-25T11:21:16Z"
    labels:
      app.kubernetes.io/managed-by: keda-operator
      app.kubernetes.io/name: keda-hpa-worker-autoscaler
      app.kubernetes.io/part-of: worker-autoscaler
      app.kubernetes.io/version: 2.21.0
      scaledobject.keda.sh/name: worker-autoscaler
    name: keda-hpa-worker-autoscaler
    namespace: llm-gateway
    ownerReferences:
    - apiVersion: keda.sh/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: ScaledObject
      name: worker-autoscaler
      uid: 21601533-891a-4656-a046-34cd57fc36fc
    resourceVersion: "1790340156073151022"
    uid: ddb09938-74b1-4857-9f5c-3c152d1ea70d
  spec:
    maxReplicas: 2
    metrics:
    - external:
        metric:
          name: s0-redis-inference_queue
          selector:
            matchLabels:
              scaledobject.keda.sh/name: worker-autoscaler
        target:
          averageValue: "5"
          type: AverageValue
      type: External
    minReplicas: 1
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: worker
  status:
    conditions:
    - lastTransitionTime: "2026-09-25T12:40:20Z"
      message: recommended size matches current size
      reason: ReadyForNewScale
      status: "True"
      type: AbleToScale
    - lastTransitionTime: "2026-09-25T12:42:36Z"
      message: scaling is disabled since the replica count of the target is zero
      reason: ScalingDisabled
      status: "False"
      type: ScalingActive
    - lastTransitionTime: "2026-09-25T12:40:05Z"
      message: the desired replica count is less than the minimum replica count
      reason: TooFewReplicas
      status: "True"
      type: ScalingLimited
    currentMetrics:
    - external:
        current:
          averageValue: "0"
        metric:
          name: s0-redis-inference_queue
          selector:
            matchLabels:
              scaledobject.keda.sh/name: worker-autoscaler
      type: External
    desiredReplicas: 0
    lastScaleTime: "2026-09-25T12:40:05Z"
kind: List
metadata:
  resourceVersion: ""
